# -*- coding: utf-8 -*-
"""AppKNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FXFlAN8ej6rcU6okbDy6zJeSoqdHibz3
"""

# -*- coding: utf-8 -*-
import streamlit as st
import numpy as np
import joblib

knn_model = joblib.load("knn_best_model.sav")
scaler = joblib.load("scaler.sav")


# PAGE TITLE
st.title("Health Risk Classification (KNN Model)")
st.markdown(
    """
    Predict **health risk level** using an optimized **K-Nearest Neighbors (KNN)** model
    based on lifestyle and health-related factors.
    """
)


# INPUT FORM
st.header("Input Health Data")

col1, col2 = st.columns(2)

with col1:
    st.subheader("Personal Data")
    age = st.slider("Age", 0, 100, 30)
    bmi = st.slider("BMI", 10.0, 50.0, 22.0)
    sleep = st.slider("Sleep Duration (hours)", 0.0, 12.0, 7.0)

with col2:
    st.subheader("Lifestyle Habits")
    smoking = st.selectbox("Smoking", [0, 1], help="0 = No, 1 = Yes")
    alcohol = st.selectbox("Alcohol Consumption", [0, 1], help="0 = No, 1 = Yes")
    sugar = st.slider("Sugar Intake", 0.0, 100.0, 30.0)

# LABEL MAPPING
label_map = {
    0: "High Risk",
    1: "Low Risk"
}

# PREDICTION
st.text("")
if st.button("Predict Health Risk"):
    input_data = np.array([[
        age,
        bmi,
        smoking,
        alcohol,
        sleep,
        sugar
    ]])

    input_scaled = scaler.transform(input_data)

    knn_pred = knn_model.predict(input_scaled)[0]

    st.subheader("Prediction Result")
    st.success(f"Predicted Health Risk: **{label_map[knn_pred]}**")